### ISSUE TITLE
Falsy default values not respected by apiUtils.defaultValueFromSchema

### ISSUE THREAD

**Issue by WesJourdan** [fugitivelabs/yote#148]
Falsy default values will always be set to null.

Instead of this:
`val = schemaType.defaultValue ? schemaType.defaultValue : null;`
We should do something like this:
`val = typeof schemaType.defaultValue === "boolean" ? schemaType.defaultValue : null;`
`val = typeof schemaType.defaultValue === "number" ? schemaType.defaultValue : null;`

**Comment by grantfowler** [comment]
fixed in 0.9
