### ISSUE TITLE
absolute state paths instead of "^"

### ISSUE THREAD

**Issue by grantfowler** [fugitivelabs/yote#69]
a mix of absolute and relative states can get confusing. like in dave's. lets revisit this.

**Comment by ffugly** [comment]
relative paths are more convenient with partial views when used in multiple places.  "^" acts like a relative "back" action.  and it makes it easier to drop an inherited state on the tail end of a resource.  

i.e. in Covey we can get to the same 'post-edit' state (including controllers which call factories, etc) at both /activity/:postId/edit and /group/:coveyId/:postId/edit simply by calling ```ui-sref=".edit({postId: post._id})"``` from the parent state.  this opens a modal that when closed takes you to the parent state by using "^".  This would be tougher to accomplish with an absolute path to the 'post-edit' state.
